version: "3.9"

services:

  web:
    build:
      context: ./NewTrip
      dockerfile: ./Dockerfile.prod
    command: gunicorn NewTrip.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/NewTrip/web/static
      - media_volume:/home/NewTrip/web/media
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env.prod


  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/NewTrip/web/static
      - media_volume:/home/NewTrip/web/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  db_data:
  static_volume:
  media_volume:
