# Generated by Django 4.0.5 on 2022-07-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['is_admin', 'number_phone', 'username'], 'verbose_name': 'пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
